name: staging workflow

run-name: >+
  CI Pipeline triggered by ${{github.actor}}
  on event':' ${{github.event_name}}
  -> branch':' ${{github.ref_name}}
  for repository':' ${{github.repository}}


on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd frontend && npm install
      - run: cd frontend && npm run lint -- --fix
      - run: cd frontend && npm run lint
      - run: cd frontend && npm test -- --watchAll=false
      - run: cd frontend && npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd backend  && npm install
      - run: cd backend && node --check server.js

  deploy-onstaging-ec2:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    environment:
      name: ec2-staging
      url: ${{ steps.set-url.outputs.page_url }}
    steps:
      - name: Execute remote SSH commands using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST_2 }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~/Assignment_4_Devops_CI-CD_Pipeline
            git pull origin main

            pm2 stop backend || true
            pm2 delete backend || true
            sudo docker compose -f postgres-compose.yml down -v
            sudo docker rm -f notes_postgres

            sudo docker compose -f postgres-compose.yml up -d

            sleep 10

            cd backend
            npm install
            pm2 restart backend || pm2 start server.js --name backend

            cd ../frontend
            npm install
            npm run build
            sudo chown -R $USER:$USER /var/www/html
            sudo chmod -R 755 /var/www/html
            sudo rm -f /var/www/html/*

            sudo cp -r build/* /var/www/html/

            sleep 10

            sudo systemctl reload apache2

      - name: Set Deployment URL
        id: set-url
        run: echo "page_url=http://${{ vars.HOST_2 }}" >> $GITHUB_OUTPUT

  succes-email:
    needs: deploy-onstaging-ec2
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: send succes email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.SMTP_HOST}}
          server_port: 587
          username: ${{secrets.SMTP_USERNAME}}
          password: ${{secrets.SMTP_PASSWORD}}
          subject: "Staging Deployment Successful"
          to: ${{secrets.QA_EMAIL}}
          from: "GitHub Actions"
          body: |
            Hello!
            Build job of ${{github.repository}} completed successfully!

            Access the staging app here:
            http://${{ vars.HOST_2 }}

            Triggered by: ${{ github.actor }}
            Commit: ${{ github.sha }}
            Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  failure-email:
    needs: deploy-onstaging-ec2
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.SMTP_HOST}}
          server_port: 587
          username: ${{secrets.SMTP_USERNAME}}
          password: ${{secrets.SMTP_PASSWORD}}
          subject: "Staging Deployment Failed"
          to: ${{secrets.QA_EMAIL}},${{secrets.DEV_EMAIL}}
          from: "GitHub Actions"
          body: |
            Hello!
            Build job of ${{github.repository}} failed!

            Triggered by: ${{ github.actor }}
            Commit: ${{ github.sha }}
            Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}



#in  apache configuration file, add the following lines to set up the reverse proxy for the backend API:
#ProxyPass /api http://localhost:5000/api
#ProxyPassReverse /api http://localhost:5000/api

#sudo a2enmod proxy proxy_http
#sudo systemctl restart apache2
#sudo apache2ctl configtest