name: staging workflow 

run-name: >+ 
  CI Pipeline triggered by ${{github.actor}}
  on event':' ${{github.event_name}}
  -> branch':' ${{github.ref_name}}
  for repository':' ${{github.repository}}


on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: cd frontend && npm install
      - run: cd frontend && npm run lint -- --fix
      - run: cd frontend && npm run lint
      - run: cd frontend && npm test -- --watchAll=false
      - run: cd frontend && npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-build 
          path: frontend/build/
   

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4 
        with:
          node-version: 18
      - run: cd backend  && npm install
      - run: cd backend && node --check server.js
  
  deploy-onstaging-ec2:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    environment:
      name: ec2-staging
      url: ${{ steps.set-url.outputs.page_url }}
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST_2 }}
          username: ${{ vars.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~/Assignment_4_Devops_CI-CD_Pipeline
            git pull origin main
            
            
            docker compose -f postgres-compose.yml up
            
            cd frontend
            npm install
            npm run build
            cp -r /build/* /var/www/html/
            
            cd ../backend
            npm start
            
            systemctl reload apache2
             
 
             
      - name: Set Deployment URL
        id: set-url
        run: echo "page_url=http://${{ vars.EC2_HOST }}" >> $GITHUB_OUTPUT  
             
