name: CICD Pipeline for tsting React APP A4

run-name: >+
  CI Pipeline triggered by ${{github.actor}}
  on event':' ${{github.event_name}}
  -> branch':' ${{github.ref_name}}
  for repository':' ${{github.repository}}

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - run: cd frontend & npm install
      - name: linting
        run: cd frontend & npm run lint
      - name:run unit test
        run:npm test --watchAll=false
      - name: upload test
        uses: actions/upload-artifact@v4
        with:
          name:frontend
      
     # STEP 2: Test Backend
  test-backend:
    name: Test Backend Application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install Dependencies
        working-directory: ./backend
        run: npm install
      
      - name: Check Backend Syntax
        working-directory: ./backend
        run: node --check server.js      



