name: CICD Pipeline for tsting React APP A4

run-name: >+
  CI Pipeline triggered by ${{github.actor}}
  on event':' ${{github.event_name}}
  -> branch':' ${{github.ref_name}}
  for repository':' ${{github.repository}}

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: cd frontend && npm install

      - name: Linting
        run: cd frontend && npm run lint

      - name: Run Unit Tests
        run: cd frontend && npm test -- --watchAll=false

      - name: Build Application
        run: cd frontend && npm run build

      - name: Upload Frontend Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/

  test-backend:
    name: Test Backend Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./backend
        run: cd backend && npm install

      - name: Check Backend Syntax
        working-directory: ./backend
        run: cd backend && node --check server.js

      - name: run backend
        run: cd backend && npm start

  deploy-on-AWS-EC2-Instance:
    needs: [test-frontend, test-backend]
    runs-on: ubuntu-latest
    environment:
      name: ec2-end-url
      url: ${{ steps.set-url.outputs.page_url }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Frontend Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-build/

      - name: Deploy Frontend to EC2
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -vzr --delete --omit-dir-times
          path: frontend-build/
          remote_path: /var/www/html/
          remote_host: ${{vars.EC2_HOST}}
          remote_user: ${{vars.EC2_USER}}
          remote_key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{vars.EC2_HOST}}
          username: ${{vars.EC2_USER}}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~/Assignment_4_Devops_CI-CD_Pipeline/backend
            git pull origin main      # Get latest code
            npm install               # Install dependencies
            pm2 restart backend       # Restart the running server

      - name: Set Deployment URL
        id: set-url
        run: echo "page_url=http://${{ vars.EC2_HOST }}" >> $GITHUB_OUTPUT
